"""add ai_memories embedding column

Revision ID: 5c69eb3fec4b
Revises: c47eeeb319b2
Create Date: 2026-07-14 02:05:46.247358

Hand-pruned from the autogenerated diff: autogenerate also wanted to drop 8
dataset tables that have no SQLAlchemy model (documents, subcontractors,
claims, etc. -- out of scope, not touched by this project), "fix" every
dataset column from TEXT to VARCHAR, and add back FK constraints that were
deliberately stripped when the dataset was imported (relationships live at
the SQLAlchemy layer, per project convention). None of that belongs here --
this migration does exactly one thing.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5c69eb3fec4b'
down_revision: Union[str, None] = 'c47eeeb319b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('ai_memories', sa.Column('embedding', Vector(768), nullable=True))


def downgrade() -> None:
    op.drop_column('ai_memories', 'embedding')
